use std::collections::HashMap;
use std::fs;
use std::path::PathBuf;

use xenomorph_common::config::{ConfigValue, PluginConfigs};
use xenomorph_common::parser::{
    AnonymType, BinaryExprType, Declaration, Expr, KeyValExpr, Literal, NumberType,
};
use xenomorph_common::plugins::XenoPlugin;
use xenomorph_common::semantic::{AnalyzerListener, ScopeInfo};

// ── Plugin registration ─────────────────────────────────────────────

static NAME: &str = "typescript";
static VERSION: &str = "0.1.0";
static PLUGIN: XenoPlugin = XenoPlugin {
    name: NAME,
    version: VERSION,
    initialize: None,
    provide_types: None,
    provide_annotations: None,
    register_generator: Some(create_generator),
    register_analyzer: None,
};

fn create_generator() -> Box<dyn for<'a> AnalyzerListener<'a>> {
    Box::new(TsGenerator::new())
}

#[no_mangle]
fn load() -> &'static XenoPlugin<'static> {
    &PLUGIN
}

// ── Generator listener ──────────────────────────────────────────────

struct TsGenerator {
    out: String,
    abs_path: PathBuf,
    module_path: String,
    /// Output directory override from `[plugins.typescript].output`.
    /// If None, writes .ts files next to the .xen source files.
    output_dir: Option<PathBuf>,
    /// Imported types keyed by module path, for generating destructured imports.
    imported_types: HashMap<String, Vec<String>>,
}

impl TsGenerator {
    fn new() -> Self {
        Self {
            out: String::new(),
            abs_path: PathBuf::new(),
            module_path: String::new(),
            output_dir: None,
            imported_types: HashMap::new(),
        }
    }
}

impl<'src> AnalyzerListener<'src> for TsGenerator {
    fn on_init(&mut self, plugin_configs: &PluginConfigs) {
        if let Some(ConfigValue::Table(ts_config)) = plugin_configs.get("typescript") {
            if let Some(ConfigValue::String(output)) = ts_config.get("output") {
                self.output_dir = Some(PathBuf::from(output));
            }
        }
    }

    fn on_before_module(&mut self, scope: &ScopeInfo) {
        self.abs_path = scope.abs_path.clone();
        self.module_path = scope.module_path.clone();
        self.imported_types = scope.imported_types.clone();
        self.out.clear();
        self.out
            .push_str("// Auto-generated by xenomorph-typescript — do not edit.\n\n");
    }

    fn on_before_ast(
        &mut self,
        ast: &[Declaration<'src>],
        _errors: &mut Vec<xenomorph_common::XenoError<'src>>,
    ) {
        // Generate imports from scope info (destructured)
        for decl in ast {
            if let Declaration::Import { path, .. } = decl {
                let import_path = path.join("/");
                if let Some(names) = self.imported_types.get(&import_path) {
                    if !names.is_empty() {
                        let destructured = names.join(", ");
                        self.out.push_str(&format!(
                            "import type {{ {destructured} }} from \"./{import_path}\";\n"
                        ));
                    }
                }
            }
        }

        // Generate type declarations
        for decl in ast {
            match decl {
                Declaration::TypeDecl { docs, name, t } => {
                    generate_type_decl(&mut self.out, docs, name.v, t);
                }
                _ => {}
            }
        }
    }

    fn on_after_module(&mut self, scope: &ScopeInfo) {
        let out_path = match &self.output_dir {
            Some(dir) => {
                let filename = format!(
                    "{}.ts",
                    scope
                        .module_path
                        .replace('/', std::path::MAIN_SEPARATOR_STR)
                );
                let path = dir.join(filename);
                if let Some(parent) = path.parent() {
                    let _ = fs::create_dir_all(parent);
                }
                path
            }
            None => self.abs_path.with_extension("ts"),
        };
        match fs::write(&out_path, &self.out) {
            Ok(_) => println!("✓ {} → {}", scope.module_path, out_path.display()),
            Err(e) => eprintln!("✗ {} — failed to write: {}", scope.module_path, e),
        }
    }
}

// ── Type declaration generation ─────────────────────────────────────

fn generate_type_decl(out: &mut String, docs: &Option<&str>, name: &str, t: &[Expr]) {
    let annotations: Vec<String> = t
        .iter()
        .filter_map(|e| match e {
            Expr::Annotation(n, args) => Some(format_annotation(n.v, args)),
            _ => None,
        })
        .collect();

    let type_exprs: Vec<&Expr> = t
        .iter()
        .filter(|e| !matches!(e, Expr::Annotation(..)))
        .collect();

    // JSDoc
    if docs.is_some() || !annotations.is_empty() {
        out.push_str("/**\n");
        if let Some(doc) = docs {
            for line in doc.lines() {
                out.push_str(&format!(" * {line}\n"));
            }
        }
        for ann in &annotations {
            out.push_str(&format!(" * {ann}\n"));
        }
        out.push_str(" */\n");
    }

    // Single struct → interface
    if type_exprs.len() == 1 {
        if let Expr::Struct(fields) = type_exprs[0] {
            generate_interface(out, name, fields);
            return;
        }
    }

    // Single enum → string union or discriminated union
    if type_exprs.len() == 1 {
        if let Expr::Enum(variants) = type_exprs[0] {
            generate_enum(out, name, variants);
            return;
        }
    }

    // Single set of literals → emit const + type
    if type_exprs.len() == 1 {
        if let Expr::Set(inner) = type_exprs[0] {
            if is_all_literals(inner) {
                let elems: Vec<String> = inner.iter().map(|a| anonym_type_to_ts(a)).collect();
                out.push_str(&format!(
                    "export const {name} = new Set([{}] as const);\n",
                    elems.join(", ")
                ));
                out.push_str(&format!(
                    "export type {name} = typeof {name} extends Set<infer T> ? T : never;\n\n"
                ));
                return;
            }
        }
    }

    // Everything else → type alias
    let ts = if type_exprs.is_empty() {
        "unknown".to_string()
    } else {
        type_exprs
            .iter()
            .map(|e| expr_to_ts(e))
            .collect::<Vec<_>>()
            .join(" | ")
    };
    out.push_str(&format!("export type {name} = {ts};\n\n"));
}

// ── Interface (struct) generation ───────────────────────────────────

fn generate_interface(out: &mut String, name: &str, fields: &[KeyValExpr]) {
    out.push_str(&format!("export interface {name} {{\n"));
    for (key, value) in fields {
        let (ts_type, field_annotations) = anonym_type_to_ts_with_annotations(value);
        let optional = is_nullable(value);

        if !field_annotations.is_empty() {
            out.push_str(&format!("  /** {} */\n", field_annotations.join(", ")));
        }

        let opt = if optional { "?" } else { "" };
        let ts_type = if optional {
            strip_null(&ts_type)
        } else {
            ts_type
        };
        out.push_str(&format!("  {}{opt}: {ts_type};\n", key.v));
    }
    out.push_str("}\n\n");
}

// ── Enum generation ─────────────────────────────────────────────────

fn generate_enum(out: &mut String, name: &str, variants: &[KeyValExpr]) {
    let all_simple = variants.iter().all(|(_, v)| v.is_empty());
    let all_numeric = variants
        .iter()
        .all(|(_, v)| v.len() == 1 && matches!(v.first(), Some(Expr::Literal(Literal::Number(_)))));

    if all_simple {
        let members: Vec<String> = variants
            .iter()
            .map(|(k, _)| format!("\"{}\"", k.v))
            .collect();
        out.push_str(&format!(
            "export type {name} = {};\n\n",
            members.join(" | ")
        ));
    } else if all_numeric {
        out.push_str(&format!("export enum {name} {{\n"));
        for (key, value) in variants {
            if let Some(Expr::Literal(Literal::Number(n))) = value.first() {
                let num_str = match n {
                    NumberType::Int(i, _) => i.to_string(),
                    NumberType::Float(f, _) => f.to_string(),
                };
                out.push_str(&format!("  {} = {num_str},\n", key.v));
            }
        }
        out.push_str("}\n\n");
    } else {
        let mut members: Vec<String> = Vec::new();
        for (key, value) in variants {
            if value.is_empty() {
                members.push(format!("{{ kind: \"{}\" }}", key.v));
            } else {
                let payload_ts = anonym_type_to_ts(value);
                members.push(format!("{{ kind: \"{}\"; value: {payload_ts} }}", key.v));
            }
        }
        out.push_str(&format!(
            "export type {name} =\n  | {};\n\n",
            members.join("\n  | ")
        ));
    }
}

// ── Expression → TypeScript string ──────────────────────────────────

fn expr_to_ts(expr: &Expr) -> String {
    match expr {
        Expr::Identifier(id) => builtin_to_ts(id.v).to_string(),
        Expr::Literal(lit) => literal_to_ts(lit),
        Expr::Regex(_) => "string".to_string(),
        Expr::FieldAccess(fa) => {
            let parts: Vec<&str> = fa.v.split('.').collect();
            if parts.len() == 2 {
                format!("{}[\"{}\"]", parts[0], parts[1])
            } else {
                fa.v.to_string()
            }
        }
        Expr::Not(inner) => format!("Exclude<unknown, {}>", expr_to_ts(inner)),
        Expr::BinaryExpr(op, pair) => {
            let left = expr_to_ts(&pair.0);
            let right = expr_to_ts(&pair.1);
            match op {
                BinaryExprType::Union | BinaryExprType::Or | BinaryExprType::Add => {
                    format!("{left} | {right}")
                }
                BinaryExprType::Intersection => format!("{left} & {right}"),
                BinaryExprType::Difference | BinaryExprType::Remove => {
                    format!("Exclude<{left}, {right}>")
                }
                BinaryExprType::SymmetricDifference => {
                    format!("Exclude<{left}, {right}> | Exclude<{right}, {left}>")
                }
                BinaryExprType::Xor => format!("{left} | {right}"),
                BinaryExprType::Range => format!("number /* {left}..{right} */"),
            }
        }
        Expr::List(inner) => {
            if inner.len() == 1 {
                let elem = anonym_type_to_ts(&inner[0]);
                if elem.contains('|') || elem.contains('&') {
                    format!("({elem})[]")
                } else {
                    format!("{elem}[]")
                }
            } else {
                let elems: Vec<String> = inner.iter().map(|a| anonym_type_to_ts(a)).collect();
                format!("[{}]", elems.join(", "))
            }
        }
        Expr::Set(inner) => {
            if inner.len() == 1 {
                let elem = anonym_type_to_ts(&inner[0]);
                format!("Set<{elem}>")
            } else {
                let elems: Vec<String> = inner.iter().map(|a| anonym_type_to_ts(a)).collect();
                format!("Set<{}>", elems.join(" | "))
            }
        }
        Expr::Struct(fields) => {
            let field_strs: Vec<String> = fields
                .iter()
                .map(|(k, v)| {
                    let ts = anonym_type_to_ts(v);
                    format!("{}: {ts}", k.v)
                })
                .collect();
            format!("{{ {} }}", field_strs.join("; "))
        }
        Expr::Enum(variants) => {
            let strs: Vec<String> = variants
                .iter()
                .map(|(k, v)| {
                    if v.is_empty() {
                        format!("\"{}\"", k.v)
                    } else {
                        anonym_type_to_ts(v)
                    }
                })
                .collect();
            strs.join(" | ")
        }
        Expr::Annotation(_, _) => String::new(),
    }
}

// ── AnonymType helpers ──────────────────────────────────────────────

fn anonym_type_to_ts(exprs: &AnonymType) -> String {
    let parts: Vec<String> = exprs
        .iter()
        .filter(|e| !matches!(e, Expr::Annotation(..)))
        .map(|e| expr_to_ts(e))
        .filter(|s| !s.is_empty())
        .collect();

    if parts.is_empty() {
        "unknown".to_string()
    } else if parts.len() == 1 {
        parts.into_iter().next().unwrap()
    } else {
        parts.join(" | ")
    }
}

fn anonym_type_to_ts_with_annotations(exprs: &AnonymType) -> (String, Vec<String>) {
    let mut type_parts = Vec::new();
    let mut annotations = Vec::new();

    for expr in exprs {
        match expr {
            Expr::Annotation(name, args) => {
                annotations.push(format_annotation(name.v, args));
            }
            other => {
                let ts = expr_to_ts(other);
                if !ts.is_empty() {
                    type_parts.push(ts);
                }
            }
        }
    }

    let ts = if type_parts.is_empty() {
        "unknown".to_string()
    } else if type_parts.len() == 1 {
        type_parts.into_iter().next().unwrap()
    } else {
        type_parts.join(" | ")
    };

    (ts, annotations)
}

// ── Helpers ─────────────────────────────────────────────────────────

fn builtin_to_ts(name: &str) -> &str {
    match name {
        "string" | "char" | "uuid" | "email" | "url" | "hostname" | "ip" | "ipv4" | "ipv6"
        | "semver" | "strong_password" | "date" | "datetime" | "duration" | "xml" | "yaml"
        | "toml" | "csv" | "tsv" | "regex" => "string",
        "bool" => "boolean",
        "number" | "i4" | "i8" | "i16" | "i32" | "i64" | "i128" | "u4" | "u8" | "u16" | "u32"
        | "u64" | "u128" | "f32" | "f64" | "decimal" => "number",
        "bigint" => "bigint",
        "binary" => "Uint8Array",
        "json" => "unknown",
        "any" => "any",
        "null" => "null",
        "dict" => "Record<string, unknown>",
        other => other,
    }
}

fn literal_to_ts(lit: &Literal) -> String {
    match lit {
        Literal::Number(NumberType::Int(n, _)) => n.to_string(),
        Literal::Number(NumberType::Float(f, _)) => f.to_string(),
        Literal::String(s, _) => format!("\"{s}\""),
        Literal::Boolean(b, _) => b.to_string(),
    }
}

fn format_annotation(name: &str, args: &[AnonymType]) -> String {
    if args.is_empty() || args.iter().all(|a| a.is_empty()) {
        format!("@{name}")
    } else {
        let arg_strs: Vec<String> = args.iter().map(|a| anonym_type_to_ts(a)).collect();
        format!("@{name}({})", arg_strs.join(", "))
    }
}

fn is_nullable(exprs: &AnonymType) -> bool {
    exprs.iter().any(|e| match e {
        Expr::Identifier(id) => id.v == "null",
        Expr::BinaryExpr(BinaryExprType::Union | BinaryExprType::Or, pair) => {
            is_null_expr(&pair.0) || is_null_expr(&pair.1)
        }
        _ => false,
    })
}

fn is_null_expr(expr: &Expr) -> bool {
    matches!(expr, Expr::Identifier(id) if id.v == "null")
}

fn is_all_literals(type_list: &[AnonymType]) -> bool {
    type_list.iter().all(|anon| {
        anon.iter()
            .all(|e| matches!(e, Expr::Literal(_) | Expr::Annotation(..)))
    })
}

fn strip_null(ts: &str) -> String {
    ts.split(" | ")
        .filter(|part| part.trim() != "null")
        .collect::<Vec<_>>()
        .join(" | ")
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_builtin_mappings() {
        assert_eq!(builtin_to_ts("string"), "string");
        assert_eq!(builtin_to_ts("bool"), "boolean");
        assert_eq!(builtin_to_ts("u8"), "number");
        assert_eq!(builtin_to_ts("u64"), "number");
        assert_eq!(builtin_to_ts("bigint"), "bigint");
        assert_eq!(builtin_to_ts("binary"), "Uint8Array");
        assert_eq!(builtin_to_ts("json"), "unknown");
        assert_eq!(builtin_to_ts("null"), "null");
        assert_eq!(builtin_to_ts("MyCustomType"), "MyCustomType");
    }
}
