use std::collections::HashMap;
use std::fs;
use std::path::PathBuf;

use xenomorph_common::config::{Config, ConfigValue, PluginConfigs};
use xenomorph_common::parser::{
    Annotation, Declaration, Expr, FloatSize, IntLiteral, KeyValExpr, Literal, SimpleType, Type,
    XenoType,
};
use xenomorph_common::plugins::XenoPlugin;
use xenomorph_common::semantic::{
    unsupported_target_type_diagnostic, AnalyzerListener, ScopeInfo, TypeHierarchy, XenoParent,
    XenoType as SemanticType, KEY_TRAIT,
};
use xenomorph_common::utils::{extract_documentation, relative_module_path};
use xenomorph_common::{TokenData, XenoDiagSeverity, XenoDiagnostic};

// ── Plugin registration ─────────────────────────────────────────────

static NAME: &str = "typescript";
static VERSION: &str = "0.1.2";
static PLUGIN: XenoPlugin = XenoPlugin {
    name: NAME,
    version: VERSION,
    initialize: None,
    provide_types: Some(provide_types),
    provide_annotations: None,
    provide_config_schema: Some(provide_config_schema),
    register_generator: Some(create_generator),
    register_analyzer: None,
};

static SYMBOL: SemanticType = SemanticType {
    name: "symbol",
    documentation: Some("The JavaScript symbol primitive."),
    generic_params: None,
    parents: Some(&[XenoParent::Trait(&KEY_TRAIT)]),
};

static TYPESCRIPT_TYPES: &[&SemanticType] = &[&SYMBOL];

fn provide_types() -> &'static [&'static SemanticType] {
    TYPESCRIPT_TYPES
}

fn provide_config_schema() -> &'static str {
    r#"{
        "type": "object",
        "description": "TypeScript type declaration generator.",
        "properties": {
            "output": {
                "type": "string",
                "description": "Output directory for generated .ts files, relative to the workspace root. If omitted, files are written next to their .xen sources."
            }
        },
        "additionalProperties": false
    }"#
}

fn create_generator(plugin_configs: &PluginConfigs) -> Box<dyn for<'a> AnalyzerListener<'a>> {
    let mut generator = TsGenerator::new();
    if let Some(ConfigValue::Table(ts_config)) = plugin_configs.get("typescript") {
        if let Some(ConfigValue::String(output)) = ts_config.get("output") {
            generator.output_dir = Some(PathBuf::from(output));
        }
    }
    Box::new(generator)
}

#[no_mangle]
fn load() -> &'static XenoPlugin<'static> {
    &PLUGIN
}

// ── Generator listener ──────────────────────────────────────────────

struct TsGenerator {
    out: String,
    abs_path: PathBuf,
    module_path: String,
    /// Output directory override from `[plugins.typescript].output`.
    /// If None, writes .ts files next to the .xen source files.
    output_dir: Option<PathBuf>,
    /// Imported types keyed by module path, for generating destructured imports.
    imported_types: HashMap<String, Vec<String>>,
    /// Complete semantic graph used to distinguish generated declarations
    /// from static types that require an explicit TypeScript mapping.
    type_hierarchy: TypeHierarchy,
    /// Nesting depth while walking annotation arguments, which are metadata
    /// rather than emitted TypeScript value types.
    annotation_depth: usize,
}

impl TsGenerator {
    fn new() -> Self {
        Self {
            out: String::new(),
            abs_path: PathBuf::new(),
            module_path: String::new(),
            output_dir: None,
            imported_types: HashMap::new(),
            type_hierarchy: TypeHierarchy::default(),
            annotation_depth: 0,
        }
    }
}

impl<'src> AnalyzerListener<'src> for TsGenerator {
    fn on_before_module(&mut self, scope: &ScopeInfo) {
        self.abs_path = scope.abs_path.clone();
        self.module_path = scope.module_path.clone();
        self.imported_types = scope.imported_types.clone();
        self.type_hierarchy = scope.type_hierarchy.clone();
        self.annotation_depth = 0;
        self.out.clear();
        self.out
            .push_str("// Auto-generated by xenomorph-typescript — do not edit.\n\n");

        let mut imports: Vec<_> = scope.imported_types.iter().collect();
        imports.sort_by(|(left, _), (right, _)| left.cmp(right));

        for (import_path, names) in imports {
            if !names.is_empty() {
                let destructured = names.join(", ");
                let ts_import_path = ts_import_specifier(&scope.module_path, import_path);
                self.out.push_str(&format!(
                    "import type {{ {destructured} }} from \"{ts_import_path}\";\n"
                ));
            }
        }
    }

    fn on_before_ast(
        &mut self,
        ast: &[Declaration<'src>],
        _errors: &mut Vec<xenomorph_common::XenoDiagnostic<'src>>,
    ) {
        // Generate type declarations
        for decl in ast {
            match decl {
                Declaration::Type {
                    docs,
                    name,
                    generics,
                    ty: t,
                    ..
                } => {
                    generate_type_decl(&mut self.out, docs, name.v, generics.as_deref(), t);
                }
                _ => {}
            }
        }
    }

    fn on_simple_type(&mut self, ty: &SimpleType<'src>, errors: &mut Vec<XenoDiagnostic<'src>>) {
        if self.annotation_depth == 0 {
            if let Some(diagnostic) =
                unsupported_target_type_diagnostic("TypeScript", ty, &self.type_hierarchy, |name| {
                    native_type_to_ts(name).is_some()
                })
            {
                errors.push(diagnostic);
            }
        }

        let literal = match ty {
            SimpleType::Literal(literal) | SimpleType::OptionalLiteral(literal) => literal,
            _ => return,
        };
        if let Literal::Float(float) = literal {
            if !xenomorph_common::parser::decimal_roundtrips_as(&float.value, FloatSize::F64) {
                errors.push(XenoDiagnostic {
                    location: float.cast.unwrap_or(float.token).clone(),
                    message: format!(
                        "TypeScript cannot represent floating-point literal '{}' exactly with its built-in number type.",
                        float.token.v
                    ),
                    severity: XenoDiagSeverity::Err,
                });
            }
        }
    }

    fn on_before_annotation(
        &mut self,
        _name: &TokenData<'src>,
        _args: &[Expr<'src>],
        _errors: &mut Vec<XenoDiagnostic<'src>>,
    ) {
        self.annotation_depth += 1;
    }

    fn on_after_annotation(
        &mut self,
        _name: &TokenData<'src>,
        _args: &[Expr<'src>],
        _errors: &mut Vec<XenoDiagnostic<'src>>,
    ) {
        self.annotation_depth = self.annotation_depth.saturating_sub(1);
    }

    fn on_after_module(&mut self, scope: &ScopeInfo) {
        let out_path = match &self.output_dir {
            Some(dir) => {
                let filename = format!(
                    "{}.ts",
                    scope
                        .module_path
                        .replace('/', std::path::MAIN_SEPARATOR_STR)
                );
                let path = Config::get().workdir.join(dir).join(filename);
                if let Some(parent) = path.parent() {
                    let _ = fs::create_dir_all(parent);
                }
                path
            }
            None => self.abs_path.with_extension("ts"),
        };
        match fs::write(&out_path, &self.out) {
            Ok(_) => println!("✓ {} → {}", scope.module_path, out_path.display()),
            Err(e) => eprintln!("✗ {} — failed to write: {}", scope.module_path, e),
        }
    }
}

// ── Type declaration generation ─────────────────────────────────────

fn generate_type_decl(
    out: &mut String,
    docs: &Option<&str>,
    name: &str,
    generics: Option<&[(&TokenData, Option<&TokenData>)]>,
    t: &XenoType,
) {
    let annotations: Vec<String> = t.1.iter().map(format_annotation).collect();
    let generic_params = format_generic_params(generics);

    // JSDoc
    if docs.is_some() || !annotations.is_empty() {
        out.push_str("/**\n");
        if let Some(doc) = docs {
            for line in doc.lines() {
                out.push_str(&format!(" * {line}\n"));
            }
        }
        for ann in &annotations {
            out.push_str(&format!(" * {ann}\n"));
        }
        out.push_str(" */\n");
    }

    if let Type::Struct(fields) = &t.0 {
        generate_interface(out, name, &generic_params, fields);
        return;
    }

    if let Type::Enum(variants) = &t.0 {
        generate_enum(out, name, variants);
        return;
    }

    if let Type::Set(set) = &t.0 {
        if let Some(values) = &set.values {
            let elems = values.iter().map(literal_to_ts).collect::<Vec<_>>();
            let constraint = set
                .element_type
                .as_ref()
                .map_or_else(String::new, |element| {
                    format!(" satisfies readonly {}[]", simple_type_to_ts(element))
                });
            out.push_str(&format!(
                "export const {name}_TYPE_VALUES = [{}] as const{constraint};\n",
                elems.join(", ")
            ));
            out.push_str(&format!(
                "export type {name} = (typeof {name}_TYPE_VALUES)[number];\n\n"
            ));
            return;
        }
    }

    if let Type::Tuple(items) = &t.0 {
        if is_all_required_literals(items) {
            let values = items.iter().map(simple_type_to_ts).collect::<Vec<_>>();
            out.push_str(&format!(
                "export const {name}_TYPE_VALUES = [{}] as const;\n",
                values.join(", ")
            ));
            out.push_str(&format!(
                "export type {name} = typeof {name}_TYPE_VALUES;\n\n"
            ));
            return;
        }
    }

    let ts = type_to_ts(&t.0);
    out.push_str(&format!("export type {name}{generic_params} = {ts};\n\n"));
}

// ── Interface (struct) generation ───────────────────────────────────

fn generate_interface(out: &mut String, name: &str, generic_params: &str, fields: &[KeyValExpr]) {
    out.push_str(&format!("export interface {name}{generic_params} {{\n"));
    for (key, value, docs) in fields {
        let ts_type = simple_type_to_ts(value);
        let optional = is_optional(value);

        if let Some(docs) = docs {
            push_jsdoc(out, extract_documentation(docs), "  ");
        }
        let opt = if optional { "?" } else { "" };
        out.push_str(&format!("  {}{opt}: {ts_type};\n", key.v));
    }
    out.push_str("}\n\n");
}

// ── Enum generation ─────────────────────────────────────────────────

fn generate_enum(out: &mut String, name: &str, variants: &[KeyValExpr]) {
    let all_numeric = variants.iter().all(|(_, value, _)| match value {
        SimpleType::Literal(Literal::Float(_)) => true,
        SimpleType::Literal(Literal::Int(integer)) => !integer_uses_bigint(integer),
        _ => false,
    });

    if all_numeric {
        out.push_str(&format!("export enum {name} {{\n"));
        for (key, value, docs) in variants {
            if let Some(docs) = docs {
                push_jsdoc(out, extract_documentation(docs), "  ");
            }
            out.push_str(&format!("  {} = {},\n", key.v, simple_type_to_ts(value)));
        }
        out.push_str("}\n\n");
    } else {
        out.push_str(&format!("export type {name} =\n"));
        for (index, (key, value, docs)) in variants.iter().enumerate() {
            let payload_ts = simple_type_to_ts(value);
            if let Some(docs) = docs {
                push_jsdoc(out, extract_documentation(docs), "  ");
            }
            let suffix = if index + 1 == variants.len() { ";" } else { "" };
            out.push_str(&format!(
                "  | {{ kind: \"{}\"; value: {payload_ts} }}{suffix}\n",
                key.v
            ));
        }
        out.push('\n');
    }
}

// ── AST → TypeScript string ─────────────────────────────────────────

fn type_to_ts(ty: &Type) -> String {
    match ty {
        Type::Simple(simple) => optional_aware_ts(simple),
        Type::Tuple(items) => format!(
            "[{}]",
            items
                .iter()
                .map(optional_aware_ts)
                .collect::<Vec<_>>()
                .join(", ")
        ),
        Type::Set(set) => match (&set.element_type, &set.values) {
            (_, Some(values)) if values.is_empty() => "never".to_string(),
            (_, Some(values)) => values
                .iter()
                .map(literal_to_ts)
                .collect::<Vec<_>>()
                .join(" | "),
            (Some(element), None) => format!("Set<{}>", simple_type_to_ts(element)),
            (None, None) => unreachable!("the parser rejects sets without a type or prefill"),
        },
        Type::Struct(fields) => format!(
            "{{ {} }}",
            fields
                .iter()
                .map(|(key, value, docs)| format!(
                    "{}{}: {}",
                    inline_jsdoc(*docs),
                    key.v,
                    simple_type_to_ts(value)
                ))
                .collect::<Vec<_>>()
                .join("; ")
        ),
        Type::Enum(variants) => variants
            .iter()
            .map(|(key, value, docs)| {
                format!(
                    "{}{{ kind: \"{}\"; value: {} }}",
                    inline_jsdoc(*docs),
                    key.v,
                    simple_type_to_ts(value)
                )
            })
            .collect::<Vec<_>>()
            .join(" | "),
        Type::Sum(items) => items
            .iter()
            .map(optional_aware_ts)
            .collect::<Vec<_>>()
            .join(" | "),
        Type::Intersection(items) => items
            .iter()
            .map(simple_type_to_ts)
            .collect::<Vec<_>>()
            .join(" & "),
    }
}

/// Struct fields spell optionality with `?:`. Aliases, tuples, and unions have
/// no such marker, so it has to become an explicit `| undefined`.
fn optional_aware_ts(ty: &SimpleType) -> String {
    match ty.is_optional() {
        true => format!("{} | undefined", simple_type_to_ts(ty)),
        false => simple_type_to_ts(ty),
    }
}

fn simple_type_to_ts(ty: &SimpleType) -> String {
    match ty {
        SimpleType::Literal(literal) | SimpleType::OptionalLiteral(literal) => {
            literal_to_ts(literal)
        }
        SimpleType::Identifier(identifier, arguments)
        | SimpleType::OptionalIdentifier(identifier, arguments) => {
            named_type_to_ts(identifier.v, arguments.as_deref())
        }
        SimpleType::Array(identifier, arguments)
        | SimpleType::OptionalArray(identifier, arguments) => {
            format!("{}[]", named_type_to_ts(identifier.v, arguments.as_deref()))
        }
    }
}

fn named_type_to_ts(name: &str, arguments: Option<&[SimpleType]>) -> String {
    if name == "dict" {
        return match arguments {
            Some([key, value]) => format!(
                "Map<{}, {}>",
                simple_type_to_ts(key),
                simple_type_to_ts(value)
            ),
            _ => "Map<string, unknown>".to_string(),
        };
    }

    // Utilities are operations: TypeScript spells several of them differently.
    if let Some([target, ..]) = arguments {
        let target = simple_type_to_ts(target);
        match name {
            "Keyof" => return format!("keyof {target}"),
            "Required" => return format!("NonNullable<{target}>"),
            "Complete" => return format!("Required<{target}>"),
            _ => {}
        }
    }

    let base = native_type_to_ts(name).unwrap_or(name);
    match arguments {
        None => base.to_string(),
        Some(arguments) => format!(
            "{base}<{}>",
            arguments
                .iter()
                .map(simple_type_to_ts)
                .collect::<Vec<_>>()
                .join(", ")
        ),
    }
}

// ── Helpers ─────────────────────────────────────────────────────────

fn format_generic_params(generics: Option<&[(&TokenData, Option<&TokenData>)]>) -> String {
    let Some(generics) = generics.filter(|generics| !generics.is_empty()) else {
        return String::new();
    };

    format!(
        "<{}>",
        generics
            .iter()
            .map(
                |(name, constraint)| match constraint.map(|constraint| constraint.v) {
                    Some("KeyTrait") => {
                        format!("{} extends string | number | bigint | symbol", name.v)
                    }
                    _ => name.v.to_string(),
                },
            )
            .collect::<Vec<_>>()
            .join(", ")
    )
}

fn native_type_to_ts(name: &str) -> Option<&'static str> {
    Some(match name {
        "string" | "char" | "uuid" | "email" | "url" | "hostname" | "ip" | "ipv4" | "ipv6"
        | "semver" | "strong_password" | "date" | "datetime" | "duration" | "xml" | "yaml"
        | "json" | "toml" | "csv" | "tsv" => "string",
        "bool" => "boolean",
        "number" | "i4" | "i8" | "i16" | "i32" | "u4" | "u8" | "u16" | "u32" | "f32" | "f64"
        | "decimal" => "number",
        "i64" | "i128" | "u64" | "u128" | "bigint" | "integer" => "bigint",
        "binary" => "Uint8Array",
        "regex" => "RegExp",
        "any" => "any",
        "null" => "null",
        "symbol" => "symbol",
        "dict" => "Map<string, unknown>",
        _ => return None,
    })
}

fn literal_to_ts(lit: &Literal) -> String {
    match lit {
        Literal::Int(integer) if integer_uses_bigint(integer) => format!("{}n", integer.value),
        Literal::Int(integer) => integer.value.to_string(),
        Literal::Float(float) => float.value.to_string(),
        Literal::String(s, _) => format!("\"{s}\""),
        Literal::Boolean(b, _) => b.to_string(),
    }
}

fn integer_uses_bigint(integer: &IntLiteral<'_>) -> bool {
    if integer
        .cast
        .is_some_and(|cast| matches!(cast.v, "i64" | "i128" | "u64" | "u128" | "bigint"))
    {
        return true;
    }

    integer
        .value
        .to_string()
        .parse::<i64>()
        .map_or(true, |value| {
            !(-9_007_199_254_740_991..=9_007_199_254_740_991).contains(&value)
        })
}

fn format_annotation(annotation: &Annotation) -> String {
    if annotation.params.is_empty() {
        format!("@{}", annotation.ident.v)
    } else {
        let arg_strs: Vec<String> = annotation.params.iter().map(expr_to_ts).collect();
        format!("@{}({})", annotation.ident.v, arg_strs.join(", "))
    }
}

fn expr_to_ts(expr: &Expr) -> String {
    match expr {
        Expr::Regex(token) => token.v.to_string(),
        Expr::Annotation(annotation) => format_annotation(annotation),
        Expr::Type(ty) => type_to_ts(ty),
    }
}

fn is_optional(ty: &SimpleType) -> bool {
    ty.is_optional()
}

fn is_all_required_literals(types: &[SimpleType]) -> bool {
    types.iter().all(|ty| matches!(ty, SimpleType::Literal(_)))
}

fn push_jsdoc(out: &mut String, docs: &str, indent: &str) {
    out.push_str(&format_jsdoc(docs, indent));
}

fn format_jsdoc(docs: &str, indent: &str) -> String {
    let mut result = format!("{indent}/**\n");
    for line in docs.lines() {
        result.push_str(&format!("{indent} * {line}\n"));
    }
    result.push_str(&format!("{indent} */\n"));
    result
}

fn inline_jsdoc(docs: Option<&xenomorph_common::TokenData>) -> String {
    docs.map(|docs| {
        format!(
            "/** {} */ ",
            extract_documentation(docs)
                .split_whitespace()
                .collect::<Vec<_>>()
                .join(" ")
        )
    })
    .unwrap_or_default()
}

fn ts_import_specifier(from_module_path: &str, to_module_path: &str) -> String {
    relative_module_path(from_module_path, to_module_path)
}

#[cfg(test)]
mod tests {
    use super::*;
    use xenomorph_common::parser::{
        FloatLiteral, FloatRepresentation, IntegerRepresentation, IntegerSize, SetType,
    };
    use xenomorph_common::semantic::{
        OwnedType, TypeDeclarationInfo, TypeHierarchy, BUILTIN_TYPES,
    };

    #[test]
    fn test_type_and_field_docs_are_preserved() {
        let key = xenomorph_common::TokenData {
            v: "displayName",
            l: 0,
            c: 0,
        };
        let field_type = xenomorph_common::TokenData {
            v: "string",
            l: 0,
            c: 0,
        };
        let field_docs = xenomorph_common::TokenData {
            v: "/** Name shown to users. */",
            l: 0,
            c: 0,
        };
        let ty = (
            Type::Struct(vec![(
                &key,
                SimpleType::Identifier(&field_type, None),
                Some(&field_docs),
            )]),
            vec![],
        );
        let mut out = String::new();

        generate_type_decl(
            &mut out,
            &Some("A user-facing profile."),
            "Profile",
            None,
            &ty,
        );

        assert!(out.contains(" * A user-facing profile."));
        assert!(out.contains("   * Name shown to users."));
        assert!(out.contains("  displayName: string;"));
    }

    #[test]
    fn test_type_alias_includes_generic_parameters() {
        let type_parameter = xenomorph_common::TokenData { v: "T", l: 0, c: 0 };
        let constraint = xenomorph_common::TokenData {
            v: "HasLength",
            l: 0,
            c: 0,
        };
        let aliased_type = xenomorph_common::TokenData { v: "T", l: 0, c: 0 };
        let generics = [(&type_parameter, Some(&constraint))];
        let ty = (
            Type::Simple(SimpleType::Identifier(&aliased_type, None)),
            vec![],
        );
        let mut out = String::new();

        generate_type_decl(&mut out, &None, "UserName", Some(&generics), &ty);

        assert_eq!(out, "export type UserName<T> = T;\n\n");
    }

    #[test]
    fn test_interface_includes_multiple_generic_parameters() {
        let first_parameter = xenomorph_common::TokenData { v: "T", l: 0, c: 0 };
        let second_parameter = xenomorph_common::TokenData { v: "U", l: 0, c: 0 };
        let field_name = xenomorph_common::TokenData {
            v: "value",
            l: 0,
            c: 0,
        };
        let field_type = xenomorph_common::TokenData { v: "T", l: 0, c: 0 };
        let generics = [(&first_parameter, None), (&second_parameter, None)];
        let ty = (
            Type::Struct(vec![(
                &field_name,
                SimpleType::Identifier(&field_type, None),
                None,
            )]),
            vec![],
        );
        let mut out = String::new();

        generate_type_decl(&mut out, &None, "Container", Some(&generics), &ty);

        assert_eq!(
            out,
            "export interface Container<T, U> {\n  value: T;\n}\n\n"
        );
    }

    #[test]
    fn test_match_annotation_is_preserved_in_jsdoc() {
        let string_type = xenomorph_common::TokenData {
            v: "string",
            l: 0,
            c: 0,
        };
        let match_name = xenomorph_common::TokenData {
            v: "match",
            l: 0,
            c: 7,
        };
        let regex = xenomorph_common::TokenData {
            v: "/^[A-Z]+$/",
            l: 0,
            c: 13,
        };
        let ty = (
            Type::Simple(SimpleType::Identifier(&string_type, None)),
            vec![Annotation {
                ident: &match_name,
                params: vec![Expr::Regex(&regex)],
            }],
        );
        let mut out = String::new();

        generate_type_decl(&mut out, &None, "Uppercase", None, &ty);

        assert_eq!(
            out,
            "/**\n * @match(/^[A-Z]+$/)\n */\nexport type Uppercase = string;\n\n"
        );
    }

    fn token(value: &str) -> TokenData<'_> {
        TokenData {
            v: value,
            l: 0,
            c: 0,
        }
    }

    #[test]
    fn prefilled_sets_emit_a_value_constant_and_a_member_union() {
        let keyword = token("set");
        let first = token("\"a\"");
        let second = token("\"b\"");
        let closing = token("]");
        let ty = (
            Type::Set(SetType {
                keyword: &keyword,
                element_type: None,
                values: Some(vec![
                    Literal::String("a".to_string(), &first),
                    Literal::String("b".to_string(), &second),
                ]),
                last_token: &closing,
            }),
            vec![],
        );
        let mut out = String::new();

        generate_type_decl(&mut out, &None, "A", None, &ty);

        assert_eq!(
            out,
            "export const A_TYPE_VALUES = [\"a\", \"b\"] as const;\nexport type A = (typeof A_TYPE_VALUES)[number];\n\n"
        );
    }

    #[test]
    fn typed_prefilled_sets_constrain_their_values() {
        let keyword = token("set");
        let element = token("string");
        let first = token("\"a\"");
        let second = token("\"b\"");
        let closing = token("]");
        let ty = (
            Type::Set(SetType {
                keyword: &keyword,
                element_type: Some(SimpleType::Identifier(&element, None)),
                values: Some(vec![
                    Literal::String("a".to_string(), &first),
                    Literal::String("b".to_string(), &second),
                ]),
                last_token: &closing,
            }),
            vec![],
        );
        let mut out = String::new();

        generate_type_decl(&mut out, &None, "A", None, &ty);

        assert_eq!(
            out,
            "export const A_TYPE_VALUES = [\"a\", \"b\"] as const satisfies readonly string[];\nexport type A = (typeof A_TYPE_VALUES)[number];\n\n"
        );
    }

    #[test]
    fn sets_without_a_prefill_stay_collection_types() {
        let keyword = token("set");
        let element = token("string");
        let closing = token(">");
        let ty = (
            Type::Set(SetType {
                keyword: &keyword,
                element_type: Some(SimpleType::Identifier(&element, None)),
                values: None,
                last_token: &closing,
            }),
            vec![],
        );
        let mut out = String::new();

        generate_type_decl(&mut out, &None, "A", None, &ty);

        assert_eq!(out, "export type A = Set<string>;\n\n");
    }

    #[test]
    fn literal_tuples_emit_a_value_constant_and_keep_their_tuple_type() {
        let first = token("\"a\"");
        let second = token("\"b\"");
        let ty = (
            Type::Tuple(vec![
                SimpleType::Literal(Literal::String("a".to_string(), &first)),
                SimpleType::Literal(Literal::String("b".to_string(), &second)),
            ]),
            vec![],
        );
        let mut out = String::new();

        generate_type_decl(&mut out, &None, "P", None, &ty);

        assert_eq!(
            out,
            "export const P_TYPE_VALUES = [\"a\", \"b\"] as const;\nexport type P = typeof P_TYPE_VALUES;\n\n"
        );
    }

    #[test]
    fn test_builtin_mappings() {
        assert_eq!(native_type_to_ts("string"), Some("string"));
        assert_eq!(native_type_to_ts("bool"), Some("boolean"));
        assert_eq!(native_type_to_ts("u8"), Some("number"));
        assert_eq!(native_type_to_ts("u64"), Some("bigint"));
        assert_eq!(native_type_to_ts("bigint"), Some("bigint"));
        assert_eq!(native_type_to_ts("binary"), Some("Uint8Array"));
        assert_eq!(native_type_to_ts("json"), Some("string"));
        assert_eq!(native_type_to_ts("null"), Some("null"));
        assert_eq!(native_type_to_ts("symbol"), Some("symbol"));
        assert_eq!(native_type_to_ts("MyCustomType"), None);
    }

    #[test]
    fn symbol_is_a_dictionary_key_and_maps_to_the_ts_primitive() {
        assert!(SYMBOL.implements(&KEY_TRAIT));

        let mut hierarchy = TypeHierarchy::default();
        for semantic_type in BUILTIN_TYPES {
            hierarchy.insert_semantic_type(semantic_type);
        }
        hierarchy.insert_semantic_type(&SYMBOL);
        assert!(hierarchy.get_type("symbol").is_some());
        assert!(hierarchy
            .get_type("symbol")
            .is_some_and(|definition| definition
                .traits
                .iter()
                .any(|candidate| candidate.name == "KeyTrait")));
        let key_parameter = hierarchy
            .generic_parameters("dict")
            .and_then(|parameters| parameters.into_iter().next())
            .expect("dict should have a key parameter");
        assert_eq!(key_parameter.constraint.as_deref(), Some("KeyTrait"));
        assert!(hierarchy.satisfies_constraint(
            &OwnedType::named("symbol"),
            key_parameter
                .constraint
                .as_deref()
                .expect("dict keys should be constrained"),
            key_parameter.constraint_scope.as_deref(),
        ));

        let dict = TokenData {
            v: "dict",
            l: 0,
            c: 0,
        };
        let symbol = TokenData {
            v: "symbol",
            l: 0,
            c: 0,
        };
        let value = TokenData {
            v: "string",
            l: 0,
            c: 0,
        };
        let ty = SimpleType::Identifier(
            &dict,
            Some(vec![
                SimpleType::Identifier(&symbol, None),
                SimpleType::Identifier(&value, None),
            ]),
        );

        assert_eq!(simple_type_to_ts(&ty), "Map<symbol, string>");

        let wide_integer = TokenData {
            v: "u64",
            l: 0,
            c: 0,
        };
        let wide_integer_dict = SimpleType::Identifier(
            &dict,
            Some(vec![
                SimpleType::Identifier(&wide_integer, None),
                SimpleType::Identifier(&value, None),
            ]),
        );
        assert_eq!(simple_type_to_ts(&wide_integer_dict), "Map<bigint, string>");
    }

    #[test]
    fn typescript_reports_static_types_without_an_explicit_mapping() {
        static MARKER: SemanticType = SemanticType {
            name: "Marker",
            documentation: None,
            generic_params: None,
            parents: None,
        };
        let marker = TokenData {
            v: "Marker",
            l: 0,
            c: 0,
        };
        let ty = SimpleType::Identifier(&marker, None);
        let mut generator = TsGenerator::new();
        generator.type_hierarchy.insert_semantic_type(&MARKER);
        let mut errors = Vec::new();

        generator.on_simple_type(&ty, &mut errors);

        assert_eq!(errors.len(), 1);
        assert_eq!(
            errors[0].message,
            "TypeScript cannot represent type 'Marker' because it has no native mapping."
        );
    }

    #[test]
    fn typescript_reports_aliases_to_unmapped_static_types() {
        static MARKER: SemanticType = SemanticType {
            name: "Marker",
            documentation: None,
            generic_params: None,
            parents: None,
        };
        let alias = TokenData {
            v: "Alias",
            l: 0,
            c: 0,
        };
        let ty = SimpleType::Identifier(&alias, None);
        let mut generator = TsGenerator::new();
        generator.type_hierarchy.set_current_module("test");
        generator.type_hierarchy.register_module("test", Vec::new());
        generator.type_hierarchy.insert_semantic_type(&MARKER);
        generator.type_hierarchy.insert_declaration(
            "test",
            "Alias",
            TypeDeclarationInfo {
                generic_params: Vec::new(),
                parents: vec![OwnedType::named("Marker")],
                body: OwnedType::named("Marker"),
                transparent_alias: true,
            },
        );
        let mut errors = Vec::new();

        generator.on_simple_type(&ty, &mut errors);

        assert_eq!(errors.len(), 1);
        assert_eq!(
            errors[0].message,
            "TypeScript cannot represent type 'Marker' because it has no native mapping."
        );
    }

    #[test]
    fn key_trait_generics_include_all_native_typescript_key_types() {
        let parameter = TokenData { v: "K", l: 0, c: 0 };
        let constraint = TokenData {
            v: "KeyTrait",
            l: 0,
            c: 3,
        };

        assert_eq!(
            format_generic_params(Some(&[(&parameter, Some(&constraint))])),
            "<K extends string | number | bigint | symbol>"
        );
    }

    #[test]
    fn integer_literals_use_number_or_bigint_without_precision_loss() {
        let safe_token = TokenData {
            v: "9007199254740991",
            l: 0,
            c: 0,
        };
        let unsafe_token = TokenData {
            v: "9007199254740992",
            l: 0,
            c: 0,
        };
        let u64_token = TokenData {
            v: "u64",
            l: 0,
            c: 20,
        };
        let safe = Literal::Int(IntLiteral {
            value: 9_007_199_254_740_991_i64.into(),
            representation: IntegerRepresentation {
                signed: false,
                size: IntegerSize::Bits(53),
            },
            token: &safe_token,
            cast: None,
        });
        let unsafe_integer = Literal::Int(IntLiteral {
            value: 9_007_199_254_740_992_i64.into(),
            representation: IntegerRepresentation {
                signed: false,
                size: IntegerSize::Bits(54),
            },
            token: &unsafe_token,
            cast: None,
        });
        let explicit_u64 = Literal::Int(IntLiteral {
            value: 1.into(),
            representation: IntegerRepresentation {
                signed: false,
                size: IntegerSize::Bits(64),
            },
            token: &safe_token,
            cast: Some(&u64_token),
        });

        assert_eq!(literal_to_ts(&safe), "9007199254740991");
        assert_eq!(literal_to_ts(&unsafe_integer), "9007199254740992n");
        assert_eq!(literal_to_ts(&explicit_u64), "1n");
    }

    #[test]
    fn overprecise_float_reports_a_generation_error() {
        let token = TokenData {
            v: "1.234567890123456789",
            l: 0,
            c: 0,
        };
        let ty = SimpleType::Literal(Literal::Float(FloatLiteral {
            value: token.v.parse().expect("valid decimal"),
            representation: FloatRepresentation {
                signed: true,
                precision: 19,
                scale: 18,
                size: FloatSize::Decimal,
            },
            token: &token,
            cast: None,
        }));
        let mut generator = TsGenerator::new();
        let mut errors = Vec::new();

        generator.on_simple_type(&ty, &mut errors);

        assert_eq!(errors.len(), 1);
        assert!(errors[0].message.contains("cannot represent"));
    }

    #[test]
    fn exactly_representable_decimal_cast_uses_number() {
        let token = TokenData {
            v: "1.25",
            l: 0,
            c: 0,
        };
        let decimal = TokenData {
            v: "decimal",
            l: 0,
            c: 8,
        };
        let literal = Literal::Float(FloatLiteral {
            value: token.v.parse().expect("valid decimal"),
            representation: FloatRepresentation {
                signed: true,
                precision: 3,
                scale: 2,
                size: FloatSize::Decimal,
            },
            token: &token,
            cast: Some(&decimal),
        });
        let ty = SimpleType::Literal(literal.clone());
        let mut generator = TsGenerator::new();
        let mut errors = Vec::new();

        generator.on_simple_type(&ty, &mut errors);

        assert!(errors.is_empty());
        assert_eq!(literal_to_ts(&literal), "1.25");
    }

    #[test]
    fn test_ts_import_specifier_for_sibling_module() {
        assert_eq!(
            ts_import_specifier("models/user", "models/address"),
            "./address"
        );
    }

    #[test]
    fn test_ts_import_specifier_for_nested_module() {
        assert_eq!(
            ts_import_specifier("models/user", "models/common/address"),
            "./common/address"
        );
    }

    #[test]
    fn test_ts_import_specifier_for_parent_module() {
        assert_eq!(
            ts_import_specifier("models/user/profile", "models/address"),
            "../address"
        );
    }

    #[test]
    fn test_ts_import_specifier_for_different_root_branch() {
        assert_eq!(
            ts_import_specifier("features/auth/user", "shared/address"),
            "../../shared/address"
        );
    }

    #[test]
    fn test_ts_import_specifier_for_root_module() {
        assert_eq!(
            ts_import_specifier("main", "shared/address"),
            "./shared/address"
        );
    }
}
