use std::collections::HashMap;
use std::fs;
use std::path::PathBuf;

use xenomorph_common::config::{ConfigValue, PluginConfigs};
use xenomorph_common::parser::{
    Annotation, Declaration, Expr, KeyValExpr, Literal, SimpleType, Type, XenoType,
};
use xenomorph_common::plugins::XenoPlugin;
use xenomorph_common::semantic::{AnalyzerListener, ScopeInfo};
use xenomorph_common::utils::extract_documentation;

// ── Plugin registration ─────────────────────────────────────────────

static NAME: &str = "typescript";
static VERSION: &str = "0.1.0";
static PLUGIN: XenoPlugin = XenoPlugin {
    name: NAME,
    version: VERSION,
    initialize: None,
    provide_types: None,
    provide_annotations: None,
    provide_config_schema: Some(provide_config_schema),
    register_generator: Some(create_generator),
    register_analyzer: None,
};

fn provide_config_schema() -> &'static str {
    r#"{
        "type": "object",
        "description": "TypeScript type declaration generator.",
        "properties": {
            "output": {
                "type": "string",
                "description": "Output directory for generated .ts files, relative to the workspace root. If omitted, files are written next to their .xen sources."
            }
        },
        "additionalProperties": false
    }"#
}

fn create_generator(plugin_configs: &PluginConfigs) -> Box<dyn for<'a> AnalyzerListener<'a>> {
    let mut generator = TsGenerator::new();
    if let Some(ConfigValue::Table(ts_config)) = plugin_configs.get("typescript") {
        if let Some(ConfigValue::String(output)) = ts_config.get("output") {
            generator.output_dir = Some(PathBuf::from(output));
        }
    }
    Box::new(generator)
}

#[no_mangle]
fn load() -> &'static XenoPlugin<'static> {
    &PLUGIN
}

// ── Generator listener ──────────────────────────────────────────────

struct TsGenerator {
    out: String,
    abs_path: PathBuf,
    module_path: String,
    /// Output directory override from `[plugins.typescript].output`.
    /// If None, writes .ts files next to the .xen source files.
    output_dir: Option<PathBuf>,
    /// Imported types keyed by module path, for generating destructured imports.
    imported_types: HashMap<String, Vec<String>>,
}

impl TsGenerator {
    fn new() -> Self {
        Self {
            out: String::new(),
            abs_path: PathBuf::new(),
            module_path: String::new(),
            output_dir: None,
            imported_types: HashMap::new(),
        }
    }
}

impl<'src> AnalyzerListener<'src> for TsGenerator {
    fn on_before_module(&mut self, scope: &ScopeInfo) {
        self.abs_path = scope.abs_path.clone();
        self.module_path = scope.module_path.clone();
        self.imported_types = scope.imported_types.clone();
        self.out.clear();
        self.out
            .push_str("// Auto-generated by xenomorph-typescript — do not edit.\n\n");

        let mut imports: Vec<_> = scope.imported_types.iter().collect();
        imports.sort_by(|(left, _), (right, _)| left.cmp(right));

        for (import_path, names) in imports {
            if !names.is_empty() {
                let destructured = names.join(", ");
                let ts_import_path = ts_import_specifier(&scope.module_path, import_path);
                self.out.push_str(&format!(
                    "import type {{ {destructured} }} from \"{ts_import_path}\";\n"
                ));
            }
        }
    }

    fn on_before_ast(
        &mut self,
        ast: &[Declaration<'src>],
        _errors: &mut Vec<xenomorph_common::XenoDiagnostic<'src>>,
    ) {
        // Generate type declarations
        for decl in ast {
            match decl {
                Declaration::Type {
                    docs, name, ty: t, ..
                } => {
                    generate_type_decl(&mut self.out, docs, name.v, t);
                }
                _ => {}
            }
        }
    }

    fn on_after_module(&mut self, scope: &ScopeInfo) {
        let out_path = match &self.output_dir {
            Some(dir) => {
                let filename = format!(
                    "{}.ts",
                    scope
                        .module_path
                        .replace('/', std::path::MAIN_SEPARATOR_STR)
                );
                let path = dir.join(filename);
                if let Some(parent) = path.parent() {
                    let _ = fs::create_dir_all(parent);
                }
                path
            }
            None => self.abs_path.with_extension("ts"),
        };
        match fs::write(&out_path, &self.out) {
            Ok(_) => println!("✓ {} → {}", scope.module_path, out_path.display()),
            Err(e) => eprintln!("✗ {} — failed to write: {}", scope.module_path, e),
        }
    }
}

// ── Type declaration generation ─────────────────────────────────────

fn generate_type_decl(out: &mut String, docs: &Option<&str>, name: &str, t: &XenoType) {
    let annotations: Vec<String> = t.1.iter().map(format_annotation).collect();

    // JSDoc
    if docs.is_some() || !annotations.is_empty() {
        out.push_str("/**\n");
        if let Some(doc) = docs {
            for line in doc.lines() {
                out.push_str(&format!(" * {line}\n"));
            }
        }
        for ann in &annotations {
            out.push_str(&format!(" * {ann}\n"));
        }
        out.push_str(" */\n");
    }

    if let Type::Struct(fields) = &t.0 {
        generate_interface(out, name, fields);
        return;
    }

    if let Type::Enum(variants) = &t.0 {
        generate_enum(out, name, variants);
        return;
    }

    if let Type::Set(inner) = &t.0 {
        if is_all_literals(inner) {
            let elems: Vec<String> = inner.iter().map(simple_type_to_ts).collect();
            out.push_str(&format!(
                "export const {name} = new Set([{}] as const);\n",
                elems.join(", ")
            ));
            out.push_str(&format!(
                "export type {name} = typeof {name} extends Set<infer T> ? T : never;\n\n"
            ));
            return;
        }
    }

    let ts = type_to_ts(&t.0);
    out.push_str(&format!("export type {name} = {ts};\n\n"));
}

// ── Interface (struct) generation ───────────────────────────────────

fn generate_interface(out: &mut String, name: &str, fields: &[KeyValExpr]) {
    out.push_str(&format!("export interface {name} {{\n"));
    for (key, value, docs) in fields {
        let ts_type = simple_type_to_ts(value);
        let optional = is_optional(value);

        if let Some(docs) = docs {
            push_jsdoc(out, extract_documentation(docs), "  ");
        }
        let opt = if optional { "?" } else { "" };
        out.push_str(&format!("  {}{opt}: {ts_type};\n", key.v));
    }
    out.push_str("}\n\n");
}

// ── Enum generation ─────────────────────────────────────────────────

fn generate_enum(out: &mut String, name: &str, variants: &[KeyValExpr]) {
    let all_numeric = variants.iter().all(|(_, value, _)| {
        matches!(
            value,
            SimpleType::Literal(Literal::Int(_, _) | Literal::Float(_, _))
        )
    });

    if all_numeric {
        out.push_str(&format!("export enum {name} {{\n"));
        for (key, value, docs) in variants {
            if let Some(docs) = docs {
                push_jsdoc(out, extract_documentation(docs), "  ");
            }
            out.push_str(&format!("  {} = {},\n", key.v, simple_type_to_ts(value)));
        }
        out.push_str("}\n\n");
    } else {
        out.push_str(&format!("export type {name} =\n"));
        for (index, (key, value, docs)) in variants.iter().enumerate() {
            let payload_ts = simple_type_to_ts(value);
            if let Some(docs) = docs {
                push_jsdoc(out, extract_documentation(docs), "  ");
            }
            let suffix = if index + 1 == variants.len() { ";" } else { "" };
            out.push_str(&format!(
                "  | {{ kind: \"{}\"; value: {payload_ts} }}{suffix}\n",
                key.v
            ));
        }
        out.push('\n');
    }
}

// ── AST → TypeScript string ─────────────────────────────────────────

fn type_to_ts(ty: &Type) -> String {
    match ty {
        Type::Simple(simple) => simple_type_to_ts(simple),
        Type::Tuple(items) => format!(
            "[{}]",
            items
                .iter()
                .map(simple_type_to_ts)
                .collect::<Vec<_>>()
                .join(", ")
        ),
        Type::Set(items) => format!(
            "Set<{}>",
            items
                .iter()
                .map(simple_type_to_ts)
                .collect::<Vec<_>>()
                .join(" | ")
        ),
        Type::Struct(fields) => format!(
            "{{ {} }}",
            fields
                .iter()
                .map(|(key, value, docs)| format!(
                    "{}{}: {}",
                    inline_jsdoc(*docs),
                    key.v,
                    simple_type_to_ts(value)
                ))
                .collect::<Vec<_>>()
                .join("; ")
        ),
        Type::Enum(variants) => variants
            .iter()
            .map(|(key, value, docs)| {
                format!(
                    "{}{{ kind: \"{}\"; value: {} }}",
                    inline_jsdoc(*docs),
                    key.v,
                    simple_type_to_ts(value)
                )
            })
            .collect::<Vec<_>>()
            .join(" | "),
        Type::Sum(items) => items
            .iter()
            .map(simple_type_to_ts)
            .collect::<Vec<_>>()
            .join(" | "),
        Type::Intersection(items) => items
            .iter()
            .map(simple_type_to_ts)
            .collect::<Vec<_>>()
            .join(" & "),
    }
}

fn simple_type_to_ts(ty: &SimpleType) -> String {
    match ty {
        SimpleType::Literal(literal) | SimpleType::OptionalLiteral(literal) => {
            literal_to_ts(literal)
        }
        SimpleType::Identifier(identifier) | SimpleType::OptionalIdentifier(identifier) => {
            builtin_to_ts(identifier.v).to_string()
        }
        SimpleType::Array(identifier) | SimpleType::OptionalArray(identifier) => {
            format!("{}[]", builtin_to_ts(identifier.v))
        }
    }
}

// ── Helpers ─────────────────────────────────────────────────────────

fn builtin_to_ts(name: &str) -> &str {
    match name {
        "string" | "char" | "uuid" | "email" | "url" | "hostname" | "ip" | "ipv4" | "ipv6"
        | "semver" | "strong_password" | "date" | "datetime" | "duration" | "xml" | "yaml"
        | "json" | "toml" | "csv" | "tsv" => "string",
        "bool" => "boolean",
        "number" | "i4" | "i8" | "i16" | "i32" | "i64" | "i128" | "u4" | "u8" | "u16" | "u32"
        | "u64" | "u128" | "f32" | "f64" | "decimal" => "number",
        "bigint" => "bigint",
        "binary" => "Uint8Array",
        "regex" => "RegExp",
        "any" => "any",
        "null" => "null",
        "dict" => "Record<string, unknown>",
        other => other,
    }
}

fn literal_to_ts(lit: &Literal) -> String {
    match lit {
        Literal::Int(n, _) => n.to_string(),
        Literal::Float(f, _) => f.to_string(),
        Literal::String(s, _) => format!("\"{s}\""),
        Literal::Boolean(b, _) => b.to_string(),
    }
}

fn format_annotation(annotation: &Annotation) -> String {
    if annotation.params.is_empty() {
        format!("@{}", annotation.ident.v)
    } else {
        let arg_strs: Vec<String> = annotation.params.iter().map(expr_to_ts).collect();
        format!("@{}({})", annotation.ident.v, arg_strs.join(", "))
    }
}

fn expr_to_ts(expr: &Expr) -> String {
    match expr {
        Expr::Regex(token) => token.v.to_string(),
        Expr::Annotation(annotation) => format_annotation(annotation),
        Expr::Type(ty) => type_to_ts(ty),
    }
}

fn is_optional(ty: &SimpleType) -> bool {
    matches!(
        ty,
        SimpleType::OptionalLiteral(_)
            | SimpleType::OptionalIdentifier(_)
            | SimpleType::OptionalArray(_)
    )
}

fn is_all_literals(types: &[SimpleType]) -> bool {
    types
        .iter()
        .all(|ty| matches!(ty, SimpleType::Literal(_) | SimpleType::OptionalLiteral(_)))
}

fn push_jsdoc(out: &mut String, docs: &str, indent: &str) {
    out.push_str(&format_jsdoc(docs, indent));
}

fn format_jsdoc(docs: &str, indent: &str) -> String {
    let mut result = format!("{indent}/**\n");
    for line in docs.lines() {
        result.push_str(&format!("{indent} * {line}\n"));
    }
    result.push_str(&format!("{indent} */\n"));
    result
}

fn inline_jsdoc(docs: Option<&xenomorph_common::TokenData>) -> String {
    docs.map(|docs| {
        format!(
            "/** {} */ ",
            extract_documentation(docs)
                .split_whitespace()
                .collect::<Vec<_>>()
                .join(" ")
        )
    })
    .unwrap_or_default()
}

fn ts_import_specifier(from_module_path: &str, to_module_path: &str) -> String {
    let mut from_dir = module_path_parts(from_module_path);
    from_dir.pop();

    let to_parts = module_path_parts(to_module_path);
    let common_len = from_dir
        .iter()
        .zip(&to_parts)
        .take_while(|(left, right)| left == right)
        .count();

    let mut relative_parts = vec![".."; from_dir.len().saturating_sub(common_len)];
    relative_parts.extend(to_parts[common_len..].iter().copied());

    let path = relative_parts.join("/");
    if path.starts_with("..") {
        path
    } else {
        format!("./{path}")
    }
}

fn module_path_parts(module_path: &str) -> Vec<&str> {
    module_path
        .split(['/', '\\'])
        .filter(|part| !part.is_empty())
        .collect()
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_type_and_field_docs_are_preserved() {
        let key = xenomorph_common::TokenData {
            v: "displayName",
            l: 0,
            c: 0,
        };
        let field_type = xenomorph_common::TokenData {
            v: "string",
            l: 0,
            c: 0,
        };
        let field_docs = xenomorph_common::TokenData {
            v: "/** Name shown to users. */",
            l: 0,
            c: 0,
        };
        let ty = (
            Type::Struct(vec![(
                &key,
                SimpleType::Identifier(&field_type),
                Some(&field_docs),
            )]),
            vec![],
        );
        let mut out = String::new();

        generate_type_decl(&mut out, &Some("A user-facing profile."), "Profile", &ty);

        assert!(out.contains(" * A user-facing profile."));
        assert!(out.contains("   * Name shown to users."));
        assert!(out.contains("  displayName: string;"));
    }

    #[test]
    fn test_builtin_mappings() {
        assert_eq!(builtin_to_ts("string"), "string");
        assert_eq!(builtin_to_ts("bool"), "boolean");
        assert_eq!(builtin_to_ts("u8"), "number");
        assert_eq!(builtin_to_ts("u64"), "number");
        assert_eq!(builtin_to_ts("bigint"), "bigint");
        assert_eq!(builtin_to_ts("binary"), "Uint8Array");
        assert_eq!(builtin_to_ts("json"), "string");
        assert_eq!(builtin_to_ts("null"), "null");
        assert_eq!(builtin_to_ts("MyCustomType"), "MyCustomType");
    }

    #[test]
    fn test_ts_import_specifier_for_sibling_module() {
        assert_eq!(
            ts_import_specifier("models/user", "models/address"),
            "./address"
        );
    }

    #[test]
    fn test_ts_import_specifier_for_nested_module() {
        assert_eq!(
            ts_import_specifier("models/user", "models/common/address"),
            "./common/address"
        );
    }

    #[test]
    fn test_ts_import_specifier_for_parent_module() {
        assert_eq!(
            ts_import_specifier("models/user/profile", "models/address"),
            "../address"
        );
    }

    #[test]
    fn test_ts_import_specifier_for_different_root_branch() {
        assert_eq!(
            ts_import_specifier("features/auth/user", "shared/address"),
            "../../shared/address"
        );
    }

    #[test]
    fn test_ts_import_specifier_for_root_module() {
        assert_eq!(
            ts_import_specifier("main", "shared/address"),
            "./shared/address"
        );
    }
}
