#:schema ./xeno/.xenomorph/xenomorph.schema.json

extends = "./xeno/xenomorph.toml"

[parser]
entry = "xeno/index"

[plugins]
path = "./target/release/"
plugins = ["xenomorph_json_schema", "xenomorph_java", "xenomorph_typescript"]

[plugins.typescript]
output = "./tests/out/typescript/"

[plugins.json_schema]
output = "./tests/out/json_schema/"

[plugins.java]
output = "./tests/out/java/"
package = "com.xyz.model"
data = true
builder = true
