[package]
name = "xenomorph"
version = "0.1.0"
edition = "2021"

[dependencies]
xenomorph_common = { path = "../common" }
clap = { version = "4.5.31", features = ["derive"] }
libloading = { version = "0" }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
lsp-types = "0.97.0"