[package]
name = "xenomorph_lsp"
version = "0.1.0"
edition = "2021"

[dependencies]
xenomorph_common = { path = "../common" }
tower-lsp = { version = "0.20.0" }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tokio = { version = "1.28", features = ["full"] }
